
/**
* CompteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banque.idl
* Friday, September 20, 2024 11:19:23 AM WET
*/

public interface CompteOperations 
{
  double solde ();
  boolean credit (double amount);
  boolean debit (double amount);
} // interface CompteOperations
